name: Build & Push Frontend + Backend

on:
  #   push:
  #     branches: [main]

  # Manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/demo-backend:latest ./backend
          docker push ghcr.io/${{ github.repository_owner }}/demo-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/demo-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/demo-frontend:latest

      - name: Logout from GHCR
        run: docker logout ghcr.io
